---
driver:
  name: docker

verifier:
  name: inspec
  attributes:
    dnsimple_token: <%= ENV['DNSIMPLE_ACCESS_TOKEN'] %>
    test_domain: dnsimple.xyz

platforms:
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: ubuntu-18.04
- name: centos-6
- name: centos-7
