---
driver:
  name: dokken
  privileged: true
  chef_version: 14

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true
  always_update_cookbooks: true

verifier:
  name: inspec
  attributes:
    dnsimple_token: <%= ENV['DNSIMPLE_ACCESS_TOKEN'] %>
    test_domain: <%= ENV['DNSIMPLE_TEST_DOMAIN'] || 'dnsimple.xyz' %>

platforms:
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
          - RUN /usr/bin/apt-get update

  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
          - RUN /usr/bin/apt-get update

  - name: centos-6
    driver:
      image: dokken/centos-6
      pid_one_command: /sbin/init

  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd

  - name: centos-8
    driver:
      image: dokken/centos-8
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: create_record
    run_list:
      - recipe[dnsimple_test::reset_test_environment]
      - recipe[dnsimple_test::create_record]
    attributes:
      dnsimple:
        access_token: <%= ENV['DNSIMPLE_ACCESS_TOKEN'] %>
        base_url: https://api.sandbox.dnsimple.com
        test_domain: <%= ENV['DNSIMPLE_TEST_DOMAIN'] || 'dnsimple.xyz' %>
  - name: update_record
    run_list:
      - recipe[dnsimple_test::reset_test_environment]
      - recipe[dnsimple_test::update_record]
    attributes:
      dnsimple:
        access_token: <%= ENV['DNSIMPLE_ACCESS_TOKEN'] %>
        base_url: https://api.sandbox.dnsimple.com
        test_domain: <%= ENV['DNSIMPLE_TEST_DOMAIN'] || 'dnsimple.xyz' %>
